#Need database.yml in git history for elasticbeastalk

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Batter to put local db values in ENV
development:
  <<: *default
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  database: potfolio_development

production:
  <<: *default
  url: <%= ENV['INTERNAL_DATABASE_URL'] %>